version: '3.8'

services:
  backend:
    image: sallyphaan/authenticationcc:latest
    ports:
      - "8081:8081"
    networks:
      - e2e-network

  frontend:
    image: sallyphaan/frontendindividualss6:latest
    environment:
      CYPRESS_BASE_URL: "http://backend:8081"
    networks:
      - e2e-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
