services:
  frontend:
    image: sallyphaan/frontendindividualss6:latest
    container_name: frontend
    environment:
      CYPRESS_BASE_URL: "http://backend:8081"  # Adjust to backend's correct URL if needed
    networks:
      - e2e-network  # Attach to the custom network

  backend:
    image: sallyphaan/authenticationcc:latest
    container_name: backend
    ports:
      - "8081:8081"
    networks:
      - e2e-network  # Attach to the custom network

networks:
  e2e-network:
    driver: bridge  # You can also use 'host' if needed, but 'bridge' is typically fine for most use cases
