services:
  frontend:
    image: sallyphaan/frontendindividualss6:latest
    container_name: frontend
    environment:
      CYPRESS_BASE_URL: "http://backend:8081"
    networks:
      - e2e-network
    depends_on:
      - backend

  backend:
    image: sallyphaan/authenticationcc:latest
    container_name: backend
    ports:
      - "8081:8081"
    networks:
      - e2e-network

  cypress:
    image: cypress/included:13.17.0  # Official Cypress Docker image
    container_name: cypress
    environment:
      CYPRESS_baseUrl: "http://frontend:3000"  # Adjust as necessary
    depends_on:
      - frontend
    networks:
      - e2e-network
    entrypoint: npx cypress run  # This will run the Cypress tests
